# Seed nodes
addnode=maxexplorer.cloudapp.net
addnode=maxcoin.cloudapp.net
addnode=maxcoinus.cloudapp.net
addnode=maxcoinasia.cloudapp.net
addnode=213.179.202.19
addnode=wombat.dar.sh

# Enable RPC
server=1

# RPC information
rpcuser=grantlovin
rpcpassword=wtei*2789

# Mining
gen=1
